 Just A line to check git
* The 5 Elements

The 5 Elements describe the main types of energy (Taoists identified) in the physical world. Everything in the physical world (visible or invisible - including air, electromagnetic fields etc.) has the overall characteristic of one of the Elements.

Understanding their qualities and the way they interact helps us to implement Feng Shui.

* Origin

Chinese Taoists discovered a supreme natural power which they called "Wu Qi".

Wu Qi means nothingness. 
( in essense the source of everything that follows ).
All things in the spiritual realm are unified, all things in the physical world are dualities.

There have been various cross-over theories to explain this Original force in Scientific speak. 
One theory is that the "nothingness " is what Physicists describe as "Dark Matter" or subtle sub atomic entities. 
Dark Matter (according to modern physicists) makes up the majority of the universe accounting for approximately 90%,
 with the remaining 10% being the physical universe, or what we. kinda know of, as physical (planets, atmosphere, people,stuff). 
Please see the "advanced" section for more detail. 

The diagram opposite shows the transformation of energy from subtle to physical. It explains everything. From unity (Wu Qi), splitting into (Yin and Yang(duality)) and then (dependent on the quality and proportions) forming the variety of our world  (5 Elements to 64 hexagrams and beyond).

* Yin and Yang to 5 Elements

The Chinese used a binary system to describe the quality of energy. 

Yang (+'ve, male) is a solid line.
Yin (-'ve, female) is a broken line.
(please refer to the Yin & Yang section for an explanation).
Man and nature are a model of the integration of Yin and Yang. 

Physical energy is manifested as the body and  Subtle energy manifested as the mind and spirit.

TAI QI (is the balanced integration of the yin and yang).
Scientist are well aware of the 4 main forces 
strong nuclear, 
weak nuclear,
gravity and 
electromagnetism
 
The Taoists deduced that there was a 5th harmonising force (named Earth). The natural way is for the 4 forces ( fire, metal, water and wood ) to fight it out ( in conflict ). It is the earth element which harmonises. 

Fire symbolises > spirit / mental energy.

Earth symbolises >  the united, harmonising and neutral force.

Metal symbolises > characterised by gravity.

Water symbolises > aggregation, contraction, collection, condensation.

Wood symbolises > explosion, disaggregate, dispersion, dissipation.

* 5 Element Cycle

The five element cycle is the key to understanding energy exchange. There are regular and abnormal cycles which are described below.

Normal and regular (generative) cycle of energy flow. 
Fire feeds earth ( ash / nutrients ).
Earth feeds metal ( minerals ).
Metal feeds water ( metal sweats ).
Water feeds wood.
Wood feeds fire.

Earth is at the centre, with it's harmonising influence.

5 element generative cycle
Abnormal (control) cycle of energy flow. 
Fire controls metal ( melts ).
Metal controls wood ( chops ). 
Wood controls earth (  extracts ).
Earth controls water ( contains ).
Water controls fire ( extinguishes ).

Nb. There are further levels to these exchanges. e.g.. Big fire combined with small water creates steam which is very auspicious.

* Elemental Clock

Each element is more active during certain months, years and times of the day. (see horoscope section for months and years information).

The clock diagram opposite shows which organ of the body is more active at what time. You will see below (attributes table) that there are yin and yang organs. Yin organs produce, transform and store qi whilst the yang organs separate the impure and expel waste.

* 5 Element Attributes

The table below describes the common attributes of the five elements.

*** insert table
