
* The 8 Directions

The Chinese discovered that Qi (energy) had differing characteristics depending upon the direction of movement. They derived a system of reading these energetic interactions using the main Elements.

A magnetic compass (Lo Pan) is used to obtain information on orientation and qualities of energy.  It is a normal magnetic compass with additional markings to indicate the 8 directions, former and later heavenly sequences, further elemental subdivisions, portents of spaces, water dragon information and more.

* The Baguas

Bagua  is the Chinese for 8 directions.

The 8 main directions (energy types) are illustrated opposite.
These eight directions refer to the quality of energy coming from these generalised directions.

The 8 directions each have characteristics of the 5 elements. Some directions whilst being of the same element actually had distinguishing characteristics. Hence SW and NE whilst both being of the earth element differed markedly in quality. So to with W & NW (metal) and E & SE (wood). Such directions were named BIG and SMALL accordingly.

NB.The eight main directions are the most commonly used, however there are further subdivisions (down to 2 degrees) which can give a more detailed divination - for specific work (desk) and furniture positioning and the calculation of the "Water Dragon" (orientation of external water flows in relation to a building).

Heavenly Bagua. The inner Trigrams relate to the "Former Heavenly Sequence". A system derived to explain the energy of free flowing Feng.

Earthly Bagua. The outer Trigrams relate to the "Later Heavenly Sequence". A system derived to explain the exchange of energy within a building/space. Essentially the earth energy (Shui) component  inherent in the structure or gravitational effect .

The Heavenly Bagua is moveable and the Earthly Bagua is fixed. Correctly combining and reading these two Bagua's gives the portent of a particular space.

NB. The Chinese always show fire (south) at the top because it relates to the heavens(S, fire, yang) above and the earth(N, water, yin) below.

* Lo Shu ( Magic Square )

Lo Shu is a numeric magic square which said to have been found as markings the back of a Turtle.
It ties in the 8 directions and seasonal changes and relates to personal horoscope numbers. (see horoscope section to calculate your own personal number).

Odd and even numbers alternate in the periphery of the square, the four corners are even numbers, and the 5 odd numbers form a cross in the centre. Each line (vertical, horizontal and diagonal) add up to 15, which is the number of days in each of the 24 cycles of the Chinese solar year.

I have indicated how the seasons tie in as well as how the amount of Yin and Yang varies. Maximum Yin during winter, increasing Yang and decreasing Yin to mid summer and vice versa.

* Readings

To establish the overall characteristic of Qi ( energy ) within a building or space, take a magnetic compass reading at the main door opening (from the door facing outwards from the room, it is the flow of energy into the room that we are interested in).

Whilst each space contains all of the five element energies - the entry point (door position) is key to determining what element has the most influence.

E.g.. Qi flowing into a room facing south has the general characteristic of the fire element. 
The two Bagua's (Earthly and Heavenly) give insight into the properties and interactions of energy by direction. 

* Earthly Bagua ( fixed - relating to spaces)

These spaces refer to the general characteristic of an internal space. Relating to the true actual magnetic orientation of spaces within a room.

The energetic characteristics can be summarised simply, as shown below.

*** table of spaces insert

    SPACE quality of Space action/ placement
    1= knowledgehigher good, information that you need to advancebooks, reference, spiritual icons, shrine
    2= familyimmediate family, close friends, employees. sense of fellowshipfamily photos associated items
    3= wealth and healthvalue, worth, personal perception of wealth,quality of life.picture of yourself in radiant health.money, related financial items (cheque book, statements etc)
    4= famehow you appear to the outside world,others perception of yourelated financial items (cheque book, statements etc)
    5= marriage, businessclose relationships, all forms of partnership, unionpairs of items, picture of you and your partner together
    6= children, projectsnew ideas / projects, conception,design, early growthPhotos of children, intention of new project (what you what to do in the future) & current projects
    7= helpful friendsnew ideas / projects, conception,design, early growthCommunication systems,  telephone, fax, computer, Picture or list of influential people.
    8= careerlife's purpose, cauldron of talents, fusion and integration
    
* Heavenly Bagua (moveable - portents for the "fixed")
These portents tell us the interactions of free flowing energy (Qi) with the stable state of the above Earthly Bagua.

SPACEi QUALITY PORTENT
a = life / gatewaystable balanced +
b = longevityextends the life of + +
c = creates qicreates energy + + +
d = problems - sharcreates problems - hindrances - -
e = deathdisconnects energy/death - - -
f = five ghosts (ancestral )inheritance +
g = good fortunegood luck + +
h = bad influencesmalign effect _ _

*** eg
E.g.. A south facing house (door to south) has predominantly Fire Qi (energy) entering it, so the interaction to an eastward wall space ( middle of East side) would give us an exchange of wood (east) with fire (south) - wood feeds fire - hence the portent would be very beneficial (as you can see above and in the diagram, a portent "C" or creates Qi). The energetic activity in that space is very generative. This example is one of the most simple examples, the others are more complex.
A full reading is made by overlaying the former and later heavenly sequences. Combining the two trigrams (3 lines) gives a hexagram (6 lines) which describes the energetic properties of a space.

8 X 8 = 64 hexagrams which relate to the 64 hexagrams of the "I Ching". 

* Flows of energy (qi)

Flows of Qi and the eddying corner effect explain how the 8 directions are applicable to a 4 sided room.

Every space contains all the elements, we can however determine which element/s have the greatest influence and determine the overall characteristic.

 swirls

 Door position also tells us whether the Qi is more or less active.

Yang room = left sided doorway, Qi spirals clockwise. Most active, best for working activities

Yin room = right sided opening, Qi spirals anti-clockwise. Least active, best for calming ( bedrooms, relaxation etc)

Lung room  = central opening, Qi spirals both ways, yin quality to the right side of the room (calming), yang to the left (active)
