
* Advanced Theory

* Preamble

When humans lived more simply, in constant and direct contact with nature (working outside), it was easier to connect and absorb basic and subtle energies.

Chinese Taoists identified a supreme natural power which they called "WU QI".

Wu Qi means nothingness (original source) we might call it God. 

One theory is that the "nothingness" is infact "Dark Matter" & "Dark energy" (now believed to be the same thing), or subtle sub-atomic entities. “Dark Matter/Dark energy” is thought by Physicists to makes up the majority of the universe accounting for approximately 90%, with the remaining 10% being the physical universe, or what man knows to exist (planets, people, stuff ,gases, atoms).

Wu Qi fills the universe. 
Connectivity is key in Taoist metaphysics, everything is connected. Even looking at a star, not only are you connected by reflected light, you are seeing the past. 
Connecting with nature helps us to draw upon this source.

Zero point field (ZPF) is well known by scientists, it describes what is left in a vacuum (a state which cannot exist?) or nothingness. This field (or interconnected matrix linking everything in the universe) is full of subatomic activity. ZPF helps explain the Taoists belief that everything is at the centre of the universe as everything is connected to everything else.

It is this connectivity which reveals infinite possibility. Atoms constantly lose and gain energy from the sub-atomic activity occurring in the ZPF and it is this perpetual activity which creates stability.

It is likely that this field is what Taoist Alchemy is tapping into. 

* General Theory

From nothing to something, creation (see diagram opposite). Wu Qi (nothingness/unity) becomes Tai Qi (perfect balance) consisting of  the main Primordial Forces, Heaven (male,positive charge,warm, spirit) and Earth (female, negative charge, cool, life giving).

The state of Tai Qi splits into Yin and Yang the subsequent interaction and proportion gives rise to the 5 elements (something physical). This occurs instantaneously. The 5 elements describe the quality of the main subtle energies at play (duality/physical state) and  is dependant upon the proportion of yin and yang (+'ve, -'ve ) present.

This classification is for general energy quality (the 64 hexagrams give a more detailed description). Each element has its own particular quality (vibration/field of influence). Colours, sounds, shapes, direction of movement, emotions, organs (&functions) and planets have a distinct elemental quality.

The Binary system of Trigrams and Hexagrams was devised by the Taoists to gives a guide to the subtle energies and how they interact. There are 8 trigram variations which when combined (8x8) give rise to the 64 hexagrams (which you may be aware of from the “I Ching”) which describe the quality of energy. A solid line indicates Yang, a broken line indicates Yin. You read from the bottom (earthly level, gives main sex) upwards (heavenly level).


* Primrdial Force

Humans store part of the primordial forces.

At conception (sperm and egg forming the first cell) the power to draw in the primordial energy is vast. Each subsequent cell also has the power to draw in the primordial force.

Each organ stores a particular quality. e.g.. The Heart stores part of the original spirit or Primordial force (red, fire, heavenly force), and the right Kidney stores part of the primordial force that gives life (blue, water, earthly force). Chinese Alchemy practices help to connect to these forces and increase vitality.

The fusion of the primordial forces is key to Taoist Alchemy practices, (combining heaven and earth), at this point you are able to alter your DNA, rejuvenate the body, giving you a strong foundation for  spiritual development. Spiritual development is only possible with this grounding as to reach the state of Tai Qi which is the gateway to “nothingness” (god, unity), a balance of heaven and earth is required. ( the balance is a perfect imbalance, see yin & yang balance for detail). NB. The reason the "belly button" is key in "Chinese Taoist Alchemy is that this is the point at which the primordial force first enters our bodies (first cells - connection to mother).


* Feng Shui
  
The Feng Shui looks at the effect of the surrounding environment upon a site and the interaction of subtle energies within confined spaces giving guidance on suitability, arrangement, and how best to utilize. 

The core theory is exactly the same as for all Taoist Esoteric practices.
Humans, living things, objects, everything is connected and affected glued together by a vast ocean of inter connectivity filling every space.
It is best to imagine this “stuff” in terms of energy fields, exerting their own influence and being influenced. Imagine a bunch of waves, the constructive and destructive interference they create (see below). Obviously you can effect this interaction to your benefit.
NB. Nothing is static, everything is energy, so mass is just slowed down energy.
All mass has its own gravitational force (obviously the earth has the greatest effect here).  Albert Einstein redefined the simple Newtonian concept of gravitational attraction by his theory of "unified field theory" or gravity as a field of "space time" influence.

FENG ( or wind), the stuff we cannot see (in a state of duality) or electromagnetically charged particles.

[ Electro = electric charge ( both positive and negative ).

Magnetic = magnetic charge ( positive pole and negative pole ).

Electromagnetic = the interaction of the two, causing what is called interference. ]

Interference is best visualize as a pond with two stones thrown into the water, the way the ripples interact is interference. You can have constructive interference when the troughs of one meet with the peaks of the other (both with the same amplitude), and destructive interference when the peak of one meets with the peak of the other. So we are dealing with waves and how they interact.

SHUI (water) energy, inherent in physical things, simply described as gravitational force.


* Internal Alchemy

Taoism is not Taoism.The spoken and written word is always misinterpreted. Lao Tzu apparently only wrote the "Tao Te Ching" after being continually pestered. The work is a classic in condensed meaning. It contains a detailed explanation of everything. The "Hua Hua Ching", a later work , is a more straightforward description. Much mystery surrounds Lao Tzu, that he lived to a thousand years, that he didn't live, that the name was an alias.


Whilst the fundamentals are constant, how you connect is individual.
Mantak Chias' works, I found, are the best descriptions and guides (see reading list).

The aim is to advance spiritually. By rooting yourself to the earth (physical) spiritual advancement just happens.
This is achieved by connecting to the earth ( experience blue cool energy coming up from your feet to fill your whole body ), connecting to the heavens ( experienced red, hot energy coming down through the top of your head to fill your whole body ) and sucking in cosmic particle dust through your third eye (forehead). 
To mix and circulate these energies.

The diagram opposite describes it all.

NB. Old Taoists suggested that it would take between 1000-2000 hrs of standing still to connect ( see Mantak Chia "Iron Shirt Qi Gong" for the stance ).
The more you connect, the more you realize that every single bone and muscle is out of alignment, that the flows of energy are blocked. 

Flexibility is life, rigidity is death.

The more flexible you are the better energies flow, the more you will connect to the external forces and the easier it is to connect to your spiritual being.
Always start at the base, good foot contact  ( heel,side,toes,ball ) with the ground, as we want to achieve almost a zero gravity state, an alignment straight up. If your feet are not in correct contact then the rest is out of alignment, the same for knees, hips, shoulders. Think 3d (alignment, twist and muscle pull)  assume you don't know best, and move till you find the right position. The more you practice the more you will know.
Best of all use your stomach brain and not your head brain to find out.

Enough for now! ( check back later ).
