
* Horoscope
* Calculate your personal element

Your Annual number gives you your Element by year of birth.

Your Personal number gives you your Element by solar month

A  full reading will give you your day and minute of birth.


 

Your personal element gives guidance on whether you are more suited to the energies that occur in an Eastern Life or Western life environment.

Eastern Life directions  = N (water), E (wood), SE (small wood) & S (fire).

Western Life directions = NE (small earth), SW (earth), W (metal) & NW (big metal).


*** image east/west life here

N.B. The personal number is a good enough indication for assessing whether you are Eastern or Western life.

* Zodiac signs
The twelve Zodiac signs (12 year & 12 month cycle) are listed in order.

N.B. These zodiac Animals are symbolic of the energy types. So there is a symbolic animal for each Year (12 year cycle - gives overall indication), a  monthly ( 12 solar month cycle - gives further detail), and time of birth (gives even further detail). However your Personal Element is sufficient for ascertaining the best directions for you.

*** LINK Further zodiac information /wiki link
