#+TITLE:FENG SHUI & GEOMANCY
#AUTHOR:Adrian
#+Description: basic text for web site
**Write a book about practical experience**
  include stretching, exercises.
* TODO Welcome

What follows is an explaination of Taoist, Classical, Feng Shui.
It covers theory and implementation and offers advise and design suggestions.
/* Please use it as a resource to discover and promote change.
  Please remember that this is my own interpretation*/

/*I will try my best to keep it concise and easy to understand*/
** Introduction
From the beginning of history, man has tried to rationalise his connection with the environment
and higher forces (Gods).
Combining the objective world with the (human constructed) subjective world.
The subjective world being a imagined, unverifiable, external force.



Geomancy is the reading of Earths energies (which may, or may not, include planetary movements) and how we are affected.
Geo=earth, Mancy=divination or reading.

Most Ancient Cultures (Aboriginal, African, American Indian, Celtic, Chinese, Egyptian, Indian, Nordic, Mayan etc.) had some form of geomancy.

Classical School Feng Shui is, as far as I have found, the most comprehensive and well documented system.
It's primary goal is to locate and organize a building to maximize it's (energetic) potential for the benifit
of residents/users.
Whilst (just) implementing changes recommended by a knowlegable consultant should prove benificial,
gaining an understanding of the basic principles offers a way to become more aware of ones connection
to the environment.

Taoist Metaphysics, from which Feng Shui is derived, explains all creation and subsequent manifestations.
The use of symbology and myth developed over time helps to make it understandable.

In-depth, rather than just accepting and following the prescribed systems, Taoist Metaphysics can be seen as an all encompassing and detailed explanation of the origin, creation, destruction and interaction of all cosmic energies.
Energies that are known commonly, in advanced Modern Science, and the unexplained (eg. Dark Matter).
Obviously humans five senses are extremely limited in observing much of what exists as they only see, hear, smell, taste and can touch on a limited frequency level.

Romantic and suggestive interpretations that became popular in the "New Age" (1990's and 2000's).
NB. In fact many proponents of Feng Shui use bastardised methodology, with minimal use of the original theories.
*EDIT* Whilst focusing only on the system rather than having an understanding of the underlying systems it minimises the power.
They had a heavy interior design emphasis and were based on the Taoist symbology and myth rather than the specific systems derived from Taoist Metaphysics.

My take is that a basic understanding of the fundamentals helps exponentially
 in both the implementation and the activation of focused Feng Shui.

I only cover, what I believe to be, Taoist energy exchange based Classical Feng Shui.

*COMMENT*
Understanding that humans and all of the environment, and everything in it, are totally inter-connected.
And on every single level.
Levels we cannot see, hear, smell, touch are all there and all important.
Harmonising every level is the key to transcendence.
As an example: Your physical body lined up with your subtle body. Chakras positioned correctly.

Developing intuition for the presence of, an understanding of, and a sensitivity to these subtle (non visible) forces is the route to transcendence.
**** NB* The aim is advancement.
Advancement can only happen when connection to the "greater" external forces is present, natural and balanced.
NB. Who completely knows what "advancement" is. Each step reveals more, and it makes sense that to transcend involves more than you own self-contained physical reality.
I find a good visualisation to stay focused on the core focus of advancement is:
You standing on the earth.
i. Yang energy (red, fire) spiralling down through the top of your head.
ii. Yin energy (blue, water) spiralling up from the Earths core through the soles of your feet.
iii. Cosmic Particle dust spiralling into your third eye.
iv. All of these energies being mixed and spiralled in your Tandien (just below your belly button).
v. The mixing of Yang(fire) and Yin(water) creating "steam" Qi.

It is all about realising the existence of, and connecting with, external Forces.
It is a logical system based on energy(Qi) creation and interactions, primarily the
proportions of Yang (+'ve charge) and Yin (-'ve charge).
In Classical Feng Shui there is no 'hocus pocus', however Symbology and Myth are used to illustrate technical detail in an easily digestible way. (see the footnote on this page).
All calculations and implementations are based on theory and the derived systems.

/* Everything is connected, the Planets, the Elements and all the Living Things.
In Taoism, there is also the concept of a second (stomach) brain or "gut instinct" which
is a more intuitive and holistic type of intelligence.
In 'new age' speak:
What we experience externally reflects our internal universe. Hence our environment is a reflection of ourselves and vice versa. Balancing the external environment has a direct effect upon our internal condition and helps us to realise our potential. */
It is important to note that Ones own personal development is the most important aspect of Taoism (covered in greater detail later) and that Feng Shui was
** Feng Shui - General
Feng Shui is used to determine the best siting of a building in the local landscape and interior space planning including furniture layout and colour scheme suggestions.
[ The design of Emperors Palaces is documented as the primary reason for it's development. It later became commonly adopted. ]

Feng Shui theory is based on Taoist understanding of universal energy exchanges. It was mainly derived from the writings of Lao Tzu (the "Tao Te Ching" and "Hua Hua Ching"), the "I Ching" (the classic "book of change") and observation.
Initially there were a number of Feng Shui Schools focusing on specific implementations or energy exchanges.
Over time they were absorbed into one main, all encompassing, School.

The underlying theory is the same for all Taoist practices including Tai Qi Chuan, Qi Gong, Acupuncture and Internal Alchemy. It is based on the energy exchanges between humans and the environment (from planetary movement, larger landscape, close proximity, to very small internal spaces). Horoscopes of individuals are also calculated to ascertain suitability.

Feng Shui practice aims to balance environmental energies(Qi) so residents can live in greater harmony, facilitating ease of living and personal advancement.




Including the external supply of Qi to the site and internal circulation.

Receive a nice flow of energy to the building from the larger landscape, not too fast to cause harm, not too slow to be stagnant.
To be positioned in balance with the occupants.

From: receiving a good flow of energy from the larger topographical surroundings, to internal flows of energy circulating to all rooms, to the fine positioning of objects.

Qi is the, generalised, Chinese word for energy: from Heavenly ( planetary) to Earthly ( physical ), coarse to subtle.
*WuQi, TaiQi, Yin&Yang, 5 elements, 8 directions, 64 hexagrams,
There is an Original Source energy, WuQi (unified, from which everything else comes)
Then there is the duality of physical universe. Yin and Yang (-'ve and +'ve, male & female, light & dark)

All the other sub groups of Qi are variations of above ones, and include:
Cosmic Particle dust, and I am sure many others that we are still unaware of.

The energy types below are illustrated using hexagrams ( x2 trigrams ) which show the proportion of yin and yang present.
The 5 Elements, a grouping of five main energy types ( strong nuclear, weak nuclear, gravitational,electromagnetic, the Taoist added a 5th unifying element (earth) to what today's scientist call the main forces.
The 8 Directions, these are energy types, derived from the 5 Elements, based on direction. They are calculated by combining earthly (in the ground)  and heavenly (electromagnetic, free floating) directional energetic interactions.

Hence the name:
FENG = water (literal translation), energy in the ground that flows like water, gravity.
SHUI = Wind (literal translation), energy free flowing above the ground, electromagnetism.

A lot of the terminology/symbology is used to convey the complexity simply.

 based on their knowledge and explanation of creation. The Philosophy is in-depth and well thought through. In fact it could be regarded today as advanced particle (meta)physics.


The Creation of Qi (energy), it's  various general types and qualities, and it's interactions is key.

There are a number of different Schools of Feng Shui. The Form School, Compass School, Black Sect School and Flying Star School.
The Classical School was an amalgam of the Form and Compass Schools and is what I am explaining on this website.

** Feng Shui (definition)
The literal translation of Feng Shui is - Wind (&) Water.

Feng (wind) is energy (qi) that flows above the ground and fills every "space" there is.
It flows as wind, and whilst can move at any speed, relative to Shui (energy inherent in the earth) can be described as fast moving.
It's characteristics and interactions are dependent upon the environment it occupies and the direction in which it flows. It can partially be described as electromagnetically charged particles in the atmosphere.

Shui (water) is fluid energy (qi) contained within the earth and (by connection with) inherent in the structure of a building (all mass), it is slow moving.
It is experienced as a cool blue energy, hence being called water, it is essentially but not exclusively gravitational force.

/* NB There is also another main force called "cosmic particle dust", a more ethereal force, basically stardust". This force seems not to be used in Feng Shui assessments but is integral in the Martial Arts.
Cosmic particle dust contains information memory of the cosmos.

The practice of Feng Shui aims to balance energies to benefit the occupant/s. It is a system of assessing the quality of energies at play and calculating how they interact.

It should be noted that although there are many variations, essentially, in terms of suitability, it boils down to two main generalised types of environment and personal energy types. The Eastern and Western "cycle".
A building individual and/or partner with the same cycle as your personal ( horoscope ) reading is most suited.
I will go into this later on.
`
** Application
A Magnetic Compass("Lo Pan"), is used to determine site and internal spaces orientation, energies at play, interactions and portents(readings).
Qi has different characteristics dependant upon direction ( of movement ).
/* please refer to the 8 Directions section of this site for details. */

** Assessment
A Feng Shui assessment is based on orientation, personal horoscopes and other general environmental observations.

As with all critical assessment we observe and deal with the largest most impacting elements first.

Observing how a building is set in landscape is the first step.
We are ideally looking for the surrounding environment to provide a gentle, meandering flow of active life creating energy to feed the building.
We are looking to tame aggressive, fast moving destructive energy, if present, by slowing it down and smoothing it out.
Then internal flows of energy and specific spaces are observed and advise on layout and placement can be given.



*** Table to go in here from intro.html(old site)

** Feng Shui (key aims)

It Should be noted that balancing the Site, of the building, for the energies(Qi) present is most important.
Moving location (which may be the considered advise) or substantial structural changes might be beyond the scope of inhabitants at the time.
Even if residents are found not to be suited to a location and building, after a horoscope reading, it is still beneficial to balance the environment and maximise the energetic potential.
Nb. The less fixed you are in a location the less effect the environment has on you. Thus a nomad doesn't have to bother with Feng Shui.
Balancing ones own Qi is the priority.

To determine the best site/building for individuals.
To balance the property to suit the occupants, and maximise its potential.

To ensure an ample supply of good Qi into the property/space and a natural flow throughout.
Suggest changes to the buildings internal layout.
Changing locations and orientation of doors / windows to affect the main energy and its exchange of   a building / space.

Counteract malign influences.
"Shar" = bad qi ( more specifically, detrimental fast flowing or aggressive )

Position furniture, objects, working, living, sleeping areas favourably (using portents derived from Baguas).

/* Nb. Colour is a simple and effective way to manipulate the energy of rooms/spaces. using the 5 element cycle).*/


** Mythology

All ancient traditions use metaphors and myth in explanation.
Taking things "literally" can lead to misinterpretation.

Myth and symbology is an excellent way of condensing a large amount of information into a usable form. After all, the point of knowledge is to integrate it into your being.

/*
An example:
The Green Dragon is a great mythological figure in traditional Chinese culture the symbolising the Emperor. The Green Dragon is the symbol of fertility and male vigour, it also represents the East, the Wood element and the eastern side of a building. The Green Dragon has the same attributes as the element Wood. The Green Dragon is the source of rain,  water is his life blood and he breathes fire (Water feeds Wood (the dragon) and creates Fire).

 This interaction relates to what is known as *'The Eastern Life'* or the directions and elements on the Eastern Generative Cycle (water, wood, small wood and fire - N,E,SE,S).

The *'Western Life'* directions are NE,SW,W & NW and this is symbolised by the White Tiger. You may have heard of the Dragon and Tiger (left and right) side of a building and Dragon and Tiger shaped hill formations.
*/

** NB personal advancement comment
It is important to understand that the goal of Taoism is personal advancement. Balancing and maximising environmental energies by implementing Feng Shui principals is one helpful part but not exclusive in the pursuit of transcendence. In fact ones personal development through Taoist Martial Arts helps in awareness of the energies and their effect and influence.
Feng Shui alone is beneficial. However using it as a stepping stone to discover Taoist
Philosophy and subsequently engage in Martial Art (Tai Qi, Qi Gong) practices will bring more benefit.
* TODO Theory
** WuQi
WuQi is the orignal source from which the cosmos was originally born and constantly created.
It is a unity, a singlularity, not of the physical realm.
/This is not really definable in western speak./
/* It might be regarded as "*Dark Matter*", the "*God
Particle*", or (is dark matter a fabricated concept made to get away with explaining nothing.*/
scientists might call it dark matter, the god particle, or indeed anti-matter. However one describes it, if at all right, it is "nothingness"

** What is my take on Wuqi.
   Q. Are there other dimensions than we are aware of?
   A. Definately yes.
   Q. Is is in another form to what we could recognise?
   A.
** Qi & Tai Qi- microcosmic orbit(theory)
** Yin & Yang
** Origin
** 5 Elements
** 8 Directions
** The Water Dragon
/*Typical Water Course flows.*/
The Water Dragon is an important factor in assessing a site. The diagram shows the main watercourse flows.
These also apply to road positions and flows of traffic.
A further level of detail can be applied using the 5 Element Cycle, plotting watercourse flows to 7.5 degree accuracy.

/* water coursee main diagram */

*** Water Dragon - Classic South facing example

The diagram below shows simply how to position a water-course to optimum beneficial effect ( for a south facing site).

The WATER DRAGON calculation is basically derived using the 5 ELEMENTS CYCLE in respect of directional flows: accuracy is typically to 7.5 degrees

/* South water dragon diagram */

/* NB: The energetic interaction at the main entrance is  FIRE Qi ( feng ) flowing towards the site. The watercourse brings an active and newly replenished source of WOOD quality Qi (flowing from the east ). WOOD feeding FIRE is very beneficial (see the 5 element section). The best exit of the watercourse is to the NW (METAL) and underground as FIRE controls METAL. */

** Siting buildings
*Environmental forms*
The environment in which site is located and the form of the site itself is important in a Feng Shui assessment. The illustration shows how the form is read in relation to the 5 elements.

The suitability of the building and its function/s to its environment is done using the 5 element cycle.

/* e.g.. An EARTH building (terrace) in a FIRE environment (peaked mountains or facing a gable end building/s) is very beneficial for living and working - FIRE feeds EARTH.*/

/* NB. Some environmental relationships provide good short term interactions but have bad long term repercussions.*/

** Horoscope
Your Annual number gives you your Element by year of birth.

Your Personal number gives you your Element by solar month.

A  full reading will give you your day and minute of birth.

/* diagram chart of dates */
--------
Your personal element gives guidance on whether you are more suited to the energies that occur in an Eastern Life or Western life environment.

Eastern Life directions  = N (water), E (wood), SE (small wood) & S (fire).

Western Life directions = NE (small earth), SW (earth), W (metal) & NW (big metal).

/* eastern and western lo shu square diagram */

----------
*zodiac signs*
The twelve Zodiac signs (12 year & 12 month cycle) are listed in order.
/* list animals */

/* N.B. These zodiac Animals are symbolic of the energy types. So there is a symbolic animal for each Year (12 year cycle - gives overall indication), a  monthly ( 12 solar month cycle - gives further detail), and time of birth (gives even further detail). However your Personal Element is sufficient for ascertaining the best directions for you.*/

[link wiki}

* DONE Advanced
** Preamble
When humans lived more simply, in constant and direct contact with nature (working outside), it was easier to connect and absorb basic and subtle energies.
It's quite likely in ancient times that the soul / physical body was more loosely connected.
The tighter the connection the harder it is to free.

Chinese Taoists identified a supreme natural power which they called "WU QI".

Wu Qi means nothingness (original source) (we might call it God??.-definately not)
More like the force/energy that breathes life from the subtle world into the material world.
*comment* similar to the "spirit" (ethereal subtle) comes into physical body??.

*NB.* Can't be God in real terms. In that everything is essentially god. The true essence of God is "creation". If a Philosopher was to describe the function of being God it would be "someone that creates the original".

One theory is that the "nothingness" is In fact "Dark Matter" & "Dark energy" (now believed to be the same thing), or subtle sub-atomic entities. “Dark Matter/Dark energy” is thought by Physicists to makes up the majority of the universe accounting for approximately 90%, with the remaining 10% being the physical universe, or what man knows to exist (planets, people, stuff ,gases, atoms).

Wu Qi fills the universe.
Connectivity is key in Taoist metaphysics, everything is connected. Even looking at a star, not only are you connected by reflected light, you are seeing the past.
Connecting with nature helps us to draw upon this source.

/* diagram of dark matter make up */

Zero point field (ZPF) is well known by scientists, it describes what is left in a vacuum (a state which cannot exist?) or nothingness. This field (or interconnected matrix linking everything in the universe) is full of subatomic activity. ZPF helps explain the Taoists belief that everything is at the centre of the universe as everything is connected to everything else.

It is this connectivity which reveals infinite possibility. Atoms constantly lose and gain energy from the sub-atomic activity occurring in the ZPF and it is this perpetual activity which creates stability.

It is likely that this field is what Taoist Alchemy is tapping into.

*Science overlap*
maybe add a section here.


*General Theory*

From nothing to something, creation (see diagram opposite). Wu Qi (nothingness/unity) becomes Tai Qi (perfect balance) consisting of  the main Primordial Forces, Heaven (male,positive charge,warm, spirit) and Earth (female, negative charge, cool, life giving).

The state of Tai Qi splits into Yin and Yang the subsequent interaction and proportion gives rise to the 5 elements (something physical). This occurs instantaneously. The 5 elements describe the quality of the main subtle energies at play (duality/physical state) and  is dependant upon the proportion of yin and yang (+'ve, -'ve ) present.

This classification is for general energy quality (the 64 hexagrams give a more detailed description). Each element has its own particular quality (vibration/field of influence). Colours, sounds, shapes, direction of movement, emotions, organs (&functions) and planets have a distinct elemental quality.

The Binary system of Trigrams and Hexagrams was devised by the Taoists to gives a guide to the subtle energies and how they interact. There are 8 trigram variations which when combined (8x8) give rise to the 64 hexagrams (which you may be aware of from the “I Ching”) which describe the quality of energy. A solid line indicates Yang, a broken line indicates Yin. You read from the bottom (earthly level, gives main sex) upwards (heavenly level).
/* wuqi origin diagram */

*NB* Put the whole lot in and expand!!!!!!

** Personal Qi work
Add a piece about Mantak Chia etc.
Tai qi, internal alchemy, microcosmic orbit etc
* Practice
** Siting buildings
*** Environmental forms
    *comment* My take on the influence of forms/shapes in the environment is: Energy (Qi) flows, and influences other energetic flows, in a particular way that can be attributed to an element(of the 5)
The environment in which site is located and the form of the site itself is important in a Feng Shui assessment. The illustration shows how the form is read in relation to the 5 elements.

The suitability of the building and its function/s to its environment is done using the 5 element cycle.

/* e.g.. An EARTH building (terrace) in a FIRE environment (peaked mountains or facing a gable end building/s) is very beneficial for living and working - FIRE feeds EARTH.*/

/* NB. Some environmental relationships provide good short term interactions but have bad long term repercussions.*/

** The Water Dragon
/*Typical Water Course flows.*/
The Water Dragon is an important factor in assessing a site. The diagram shows the main watercourse flows.
These also apply to road positions and flows of traffic.
A further level of detail can be applied using the 5 Element Cycle, plotting watercourse flows to 7.5 degree accuracy.

/* water course main diagram */

*** Water Dragon - Classic South facing example

The diagram below shows simply how to position a water-course to optimum beneficial effect ( for a south facing site).

The WATER DRAGON calculation is basically derived using the 5 ELEMENTS CYCLE in respect of directional flows: accuracy is typically to 7.5 degrees

/* South water dragon diagram */

/* NB: The energetic interaction at the main entrance is  FIRE Qi ( feng ) flowing towards the site. The watercourse brings an active and newly replenished source of WOOD quality Qi (flowing from the east ). WOOD feeding FIRE is very beneficial (see the 5 element section). The best exit of the watercourse is to the NW (METAL) and underground as FIRE controls METAL. */

** Tai Chi, Qi Gong practice.
How to apply *Feng Shui*  principles to your environment.

*Macro* to *Micro*
