* DONE Welcome

This site explains Taoist Classical Geomancy or Feng Shui.
It covers theory and includes practical design suggestions.

/* Please use it as a resource to discover and implement change.
   With the proviso that this is my own interpretation.*/
** Introduction
Geomancy is the reading of the Earths energies (which can also include planets) and how we are affected by them.
geo=earth, mancy=divination or reading.

Most Ancient Cultures (Aboriginal, African, American Indian, Celtic, Chinese, Egyptian, Indian, Nordic, Mayan etc.) have a history of some form of geomancy.

Feng Shui, the Chinese Taoist form of Geomancy, is one of the most comprehensive and well documented explanations.
It is a very logical system based on the creation and interactions of energy(Qi).
In pure Classical Feng Shui there is no 'hocus pocus', although symbology and Myth are used (see the footnote on this page). All calculations and suggestions can be explained according to the theory and derived systems outlined in this site.

/* Everything is connected, the planets, the elements and all the living things.
In Taoism, there is the concept of a second (stomache) brain, which can be thought of as "gut instinct".
In 'new age' speak:
What we experience externally reflects our internal universe. Hence our environment is a reflection of ourselves and vice versa. Balancing the external environment has a direct effect upon our internal condition and helps us to realize our potential. */
It is important to note that Ones own personal development is the most important aspect of Taoism (covered in greater detail later) and that Feng Shui was
** Feng Shui - General
The Chinese "Taoists art of Feng Shui is used to determine the best siting and planning of a building for inhabitants.
[ The design of Palaces seemed to be the primary reason for it, although it then became commonly adopted. ]

Feng Shui theory is based on Taoist understanding of universal energy exchanges, mainly derived from the writings of Lao Tzu (the "Tao Te Ching" and "Hua Hua Ching") and the "I Ching" (the classic "book of change"). Other ideas were also absorbed over time as it developed.
The underlying theory is the same for all Taoist practices including Tai Qi Chuan, Qi Gong, Accupuncture and Internal Alchemy. It is based on the energy exchanges between humans and the environment (from planetary movement, larger landscape, close proximity, to very small internal spaces). Horoscopes of individuals are also calculated to assertain suitablity.

Feng Shui is about balancing Qi (energy) so residents can live in harmony with the environment.

Recieve a nice flow of energy to the building from the larger landscape, not too fast to cause harm, not too slow to be stagnant.
To be positioned in balance with the occupants.

From: recieving a good flow of energy from the larger topographical surroundings, to internal flows of energy circulating to all rooms, to the fine positioning of objects.

Qi is the, generalised, Chinese word for energy: from Heavenly ( planetary) to Earthly ( physical ), coarse to subtle.
*WuQi, TaiQi, Yin&Yang, 5 elemnents, 8 directions, 64 hexigrams,
There is an Original Source energy, WuQi (unified, from which everything else comes)
Then there is the duality of physical universe. Yin and Yang (-'ve and +'ve, male & female, light & dark)

All the other sub groups of Qi are variations of above ones, and include:
Cosmic Particle dust

The energy types below are illustrated using hexigrams ( x2 trigrams ) which show the proportion of yin and yang present.
The 5 Elements, a grouping of five main energy types ( strong nuclear, weak nuclear, gravitational,electromagnetic, the taoist added a 5th unifying element (earth) to what todays scientist call the main forces.
The 8 Directions, these are energy types, derived from the 5 Elements, based on direction. They are calculated by combining earthly (in the ground)  and heavenly (electomagnetic, free floating) directional energetic interactions.

Hence the name:
FENG = water (literal translation), energy in the ground that flows like water, gravity.
SHUI = Wind (literal translation), energy free flowing above the ground, electromagnatism.

A lot of the termonolgy/symbology is used to convey the complexity simply.

 based on their knowledge and explanation of creation. The Philosophy is indepth and well thought through. Infact it could be regarded today as advanced particle (meta)physics.


The Creation of Qi (energy), it's  various general types and qualities, and it's interactions is key.

There are a number of different Schools of Feng Shui. The Form School, Compass School, Black Sect School and Flying Star School.
The Classical School was an almagam of the Form and Compass Schools and is what I am explaning on this website.

** Feng Shui (definition)
Literal translation - Wind (&) Water

Feng (wind) is energy (qi) that flows above the ground and occupies every "space" there is (totally filling the void of the physical world), it flows as wind, and is fast moving. It's characteristics are dependent upon the direction in which it flows and the environment it occupies. It can be partially described as electromagnetically charged particles in the atmosphere.

Shui (water) is energy (qi) that is contained within the earth and (by connection with) inherent in the structure of a building (all mass), it is slow moving.
It is experienced as a cool blue energy, hence being called water, it is essentially gravitational force.

/* NB There is also another main force called "cosmic particle dust", a more ethereal force, basically stardust". This force seems not to be used in Feng Shui assesments but is integral in the Martial Arts.

The practice of Feng Shui aims to balance energies to benefit the occupant/s. It is a system of assessing the quality of energies at play and calculating how they interact.

It should be noted that although there are many variations, essentially, in terms of suitability, it boils down to two main generalised types of environment and personal energy types. The Eastern and Western "cycle".
A building individual and/or partner with the same cycle as your personal ( horoscope ) reading is most suited.
I will go into this later on.
`
** Aplication

A Magnetic Compass, known as a "Lo Pan", is used to determine site/space orientation, the energies at play and interactions. Qi has different characteristics dependant upon direction ( of movement ).
/* please refer to the 8 Directions section of this site for details. */


** Assessment
Assessment is based on orientation, a personal reading  and other general observations which are outlined below.

An assessment of a site begins outside (Macro) and works inwards (Micro) to smaller internal spaces.
Always consider the macro (larger) environment first as this is the main feed of Qi to the site, and work your way down to the micro (small, internal placement).

*** Table to go in here from intro.html(old site)

** Feng Shui (key aims)

It Should be noted that balancing the site for the Qi present is most important.
Moving or substansial structural changes might be beyond the scope of the inhabitants at the time.
Even if the residents are not suited on the "cycles" it is still benificial to maximize the potential.

It may be that, for the time being, the occupants are not suited to the site, and are not currently able to move immediately. Really balancing ones own qi is the most important.

To determine the best site/building for individuals.
To balance the property to suit the occupants, and maximize its potential.

To ensure an ample supply of good Qi into the property/space and a natural flow throughout.
Suggest changes to the buildings internal layout.
Changing locations and orientation of doors / windows to affect the main energy and its exchange of   a building / space.

Counteract malign influences.
"Shar" = bad qi ( more specifically, detrimental fast flowing or aggressive )

Position furniture, objects, working, living, sleeping areas favourably (using portents derived from Baguas).

/* Nb. Colour is a simple and effective way to manipulate the energy of rooms/spaces. using the 5 element cycle).*/


** Mythology

All ancient traditions use metaphors and myth in explanation.
Taking things "literally" can lead to misinterpretation.

Myth and symbology is an excellent way of condensing a large amount of information into a usable form. After all, the point of knowledge is to integrate it into your being.

/*
An example:
The Green Dragon is a great mythological figure in traditional Chinese culture the symbolising the Emperor. The Green Dragon is the symbol of fertility and male vigour, it also represents the East, the Wood element and the eastern side of a building. The Green Dragon has the same attributes as the element Wood. The Green Dragon is the source of rain,  water is his life blood and he breathes fire (Water feeds Wood (the dragon) and creates Fire).

 This interaction relates to what is known as *'The Eastern Life'* or the directions and elements on the Eastern Generative Cycle (water, wood, small wood and fire - N,E,SE,S).

The *'Western Life'* directions are NE,SW,W & NW and this is symbolised by the White Tiger. You may have heard of the Dragon and Tiger (left and right) side of a building and Dragon and Tiger shaped hill formations.
*/


* TODO Theory
** WuQi
   WuQi is the orignal source from which the cosmos was and is born/reborn.
It is a unity, a single thing, not of the physical cosmos.
/* scientists might call it dark matter, the god particle, or indeed anti-matter. However one describes it, if at all right, it is "nothingness" */

** Qi & Tai Qi- microcosmic orbit(theory)
** Yin & Yang
** Origin
** 5 Elements
** 8 Directions
** The Water Dragon
/*Typical Water Course flows.*/
The Water Dragon is an important factor in assessing a site. The diagram shows the main watercourse flows.
These also apply to road positions and flows of traffic.
A further level of detail can be applied using the 5 Element Cycle, plotting watercourse flows to 7.5 degree accuracy.

/* water coursee main diagram */

*** Water Dragon - Classic South facing example

The diagram below shows simply how to position a water-course to optimum beneficial effect ( for a south facing site).

The WATER DRAGON calculation is basically derived using the 5 ELEMENTS CYCLE in respect of directional flows: accuracy is typically to 7.5 degrees

/* South water dragon diagram */

/* NB: The energetic interaction at the main entrance is  FIRE Qi ( feng ) flowing towards the site. The watercourse brings an active and newly replenished source of WOOD quality Qi (flowing from the east ). WOOD feeding FIRE is very beneficial (see the 5 element section). The best exit of the watercourse is to the NW (METAL) and underground as FIRE controls METAL. */

** Siting buildings
*Environmental forms*
The environment in which site is located and the form of the site itself is important in a Feng Shui assessment. The illustration shows how the form is read in relation to the 5 elements.

The suitability of the building and its function/s to its environment is done using the 5 element cycle.

/* e.g.. An EARTH building (terrace) in a FIRE environment (peaked mountains or facing a gable end building/s) is very beneficial for living and working - FIRE feeds EARTH.*/

/* NB. Some environmental relationships provide good short term interactions but have bad long term repercussions.*/

** Horoscope
Your Annual number gives you your Element by year of birth.

Your Personal number gives you your Element by solar month.

A  full reading will give you your day and minute of birth.

/* diagram chart of dates */
--------
Your personal element gives guidance on whether you are more suited to the energies that occur in an Eastern Life or Western life environment.

Eastern Life directions  = N (water), E (wood), SE (small wood) & S (fire).

Western Life directions = NE (small earth), SW (earth), W (metal) & NW (big metal).

/* eastern and western lo shu square diagram */

----------
*zodiac signs*
The twelve Zodiac signs (12 year & 12 month cycle) are listed in order.
/* list animals */

/* N.B. These zodiac Animals are symbolic of the energy types. So there is a symbolic animal for each Year (12 year cycle - gives overall indication), a  monthly ( 12 solar month cycle - gives further detail), and time of birth (gives even further detail). However your Personal Element is sufficient for ascertaining the best directions for you.*/

[link wiki}



* DONE Advanced
** Preamble
When humans lived more simply, in constant and direct contact with nature (working outside), it was easier to connect and absorb basic and subtle energies.

Chinese Taoists identified a supreme natural power which they called "WU QI".

Wu Qi means nothingness (original source) we might call it God.

One theory is that the "nothingness" is infact "Dark Matter" & "Dark energy" (now believed to be the same thing), or subtle sub-atomic entities. “Dark Matter/Dark energy” is thought by Physicists to makes up the majority of the universe accounting for approximately 90%, with the remaining 10% being the physical universe, or what man knows to exist (planets, people, stuff ,gases, atoms).

Wu Qi fills the universe.
Connectivity is key in Taoist metaphysics, everything is connected. Even looking at a star, not only are you connected by reflected light, you are seeing the past.
Connecting with nature helps us to draw upon this source.

/* diagram of dark matter make up */

Zero point field (ZPF) is well known by scientists, it describes what is left in a vacuum (a state which cannot exist?) or nothingness. This field (or interconnected matrix linking everything in the universe) is full of subatomic activity. ZPF helps explain the Taoists belief that everything is at the centre of the universe as everything is connected to everything else.

It is this connectivity which reveals infinite possibility. Atoms constantly lose and gain energy from the sub-atomic activity occurring in the ZPF and it is this perpetual activity which creates stability.

It is likely that this field is what Taoist Alchemy is tapping into.

*Science overlap*
maybe add a section here.


*General Theory*

From nothing to something, creation (see diagram opposite). Wu Qi (nothingness/unity) becomes Tai Qi (perfect balance) consisting of  the main Primordial Forces, Heaven (male,positive charge,warm, spirit) and Earth (female, negative charge, cool, life giving).

The state of Tai Qi splits into Yin and Yang the subsequent interaction and proportion gives rise to the 5 elements (something physical). This occurs instantaneously. The 5 elements describe the quality of the main subtle energies at play (duality/physical state) and  is dependant upon the proportion of yin and yang (+'ve, -'ve ) present.

This classification is for general energy quality (the 64 hexagrams give a more detailed description). Each element has its own particular quality (vibration/field of influence). Colours, sounds, shapes, direction of movement, emotions, organs (&functions) and planets have a distinct elemental quality.

The Binary system of Trigrams and Hexagrams was devised by the Taoists to gives a guide to the subtle energies and how they interact. There are 8 trigram variations which when combined (8x8) give rise to the 64 hexagrams (which you may be aware of from the “I Ching”) which describe the quality of energy. A solid line indicates Yang, a broken line indicates Yin. You read from the bottom (earthly level, gives main sex) upwards (heavenly level).
/* wuqi origin diagram */

*NB* Put the whole lot in and expand!!!!!!

** Personal Qi work
Add a piece about Mantak Chia etc.
Tai qi, internal alchemy, microcosmic orbit etc
* Practice
** Siting buildings
*** Environmental forms
The environment in which site is located and the form of the site itself is important in a Feng Shui assessment. The illustration shows how the form is read in relation to the 5 elements.

The suitability of the building and its function/s to its environment is done using the 5 element cycle.

/* e.g.. An EARTH building (terrace) in a FIRE environment (peaked mountains or facing a gable end building/s) is very beneficial for living and working - FIRE feeds EARTH.*/

/* NB. Some environmental relationships provide good short term interactions but have bad long term repercussions.*/

** The Water Dragon
/*Typical Water Course flows.*/
The Water Dragon is an important factor in assessing a site. The diagram shows the main watercourse flows.
These also apply to road positions and flows of traffic.
A further level of detail can be applied using the 5 Element Cycle, plotting watercourse flows to 7.5 degree accuracy.

/* water coursee main diagram */

*** Water Dragon - Classic South facing example

The diagram below shows simply how to position a water-course to optimum beneficial effect ( for a south facing site).

The WATER DRAGON calculation is basically derived using the 5 ELEMENTS CYCLE in respect of directional flows: accuracy is typically to 7.5 degrees

/* South water dragon diagram */

/* NB: The energetic interaction at the main entrance is  FIRE Qi ( feng ) flowing towards the site. The watercourse brings an active and newly replenished source of WOOD quality Qi (flowing from the east ). WOOD feeding FIRE is very beneficial (see the 5 element section). The best exit of the watercourse is to the NW (METAL) and underground as FIRE controls METAL. */

** Tai Chi, Qi Gong practice.
How to apply *Feng Shui*  principles to your environment.

*Macro* to *Micro*
