
* Welcome

This site explains Taoist Classical Feng Shui.
It covers the basic theory, insight into more advanced metaphysics and includes  practical design suggestions. 

Please use it as a resource to discover and implement change.
/*[ I try my best to use simple succinct language ].*/
* Introduction

Geomancy is the reading of energetic interactions on earth and how they affect us. (geo=earth, mancy=divination or reading).

Most ancient cultures (Aboriginal, African, American Indian, Celtic, Chinese, Egyptian, Indian, Nordic, Mayan etc.) have their own systems of explanation.

Feng Shui, the Chinese Taoist form of Geomancy, provides one of the most comprehensive and well documented explanations.
It is a very logical and methodical system once the fundementals are grasped.
There's no magic/faith involved.
 
Don't fictionalise your experience or try to imagine something is present when it's not because you want it to be so.
If you can't feel the energies, you are not feeling the energies. Either, give up, leave it for a bit and come back, or just work at
it more. The mind directs and the energy will follow. 
* Feng Shui (general)

The Taoists explained energetic interactions with a system derived from their knowledge of creation. The theory underlying Feng Shui is the same for all Taoist practices including the Martial arts (Tai Qi Chuan, Qi Gong, etc.), Medicine (Acupuncture, Herbal remedies etc.) and Internal Alchemy.

The concept of Qi (energy) its creation, varied qualities and interactions is key.

There are a number of different Schools (approaches) of Feng Shui (Form School, Compass School, Black Sect School, Flying Star School & Classical School). The Classical School is an amalgam of traditional theories and this is explained here.

* Feng Shui (definition)

Feng (wind) is energy (qi) that flows above the ground and occupies every space there is, it flows as wind, and is fast moving. It's characteristics are dependent upon the direction in which it flows and the environment it occupies. It can be partially described as electromagnetically charged particles in the atmosphere. It is experienced as a warm energy.

Shui (water) is energy (qi) that is contained within the earth and is also inherent in the structure of a building (all mass), it is slow moving. 
It is experienced as a cool blue energy, hence being called water, it is essentially gravitational force.

The practice of Feng Shui aims to balance these energies to benefit the occupant/s. It is a system of assessing the quality of energies at play and calculating how they interact. 

* Aplication

A magnetic compass (Lo Pan) is used to determine site/space orientation, the relevant energies at play and how they interact. Qi (energy) has different characteristics Dependant upon direction.
( please refer to the 8 Directions section of this site for details).

Assessment is based on orientation, a personal reading  and other general observations which are outlined below. 

* Assessment

An assessment of the site begins outside and works inwards. 
Consider the macro (large) environment first and work your way down to the micro (small).

*** Table to go in here from intro.html(old site)

* Feng Shui (key aims)

To determine the best site/building for individuals.To balance the property to suit the occupants, maximizing potential.

Ensure an ample supply of good Qi into the property/space and a natural flow throughout.Counteract malign influences.

Orientate / position furniture, objects, working, living, sleeping areas favourably (using portents derived from Baguas).

Using colour to manipulate the energy of rooms/spaces favourably, (using the 5 element cycle).

Changing locations and orientation of doors / windows to affect the main energy and its exchange of   a building / space.

* Mythology

All ancient traditions use metaphors and myth in explanation.
An over emphasis on 'taking things literally' can lead to misinterpretation.

Myth and symbology are an excellent way of condensing a large amount of information into a usable form. After all, the point of knowledge is to integrate it into your being.

An example:
The Green Dragon is a great mythological figure in traditional Chinese culture  and is  the symbol of the Emperor. The Green Dragon is the symbol of fertility and male vigour and also represents the East, the Wood element and the eastern side of a building. The Green Dragon has the same attributes as the element Wood. (please refer to the  5 element section of this site). The Green Dragon is the source of rain,  water is his life blood and he breathes fire (Water feeds Wood (the dragon) and creates Fire). This interaction relates to what is known as 'The Eastern Life' or the directions and elements on the Eastern Generative Cycle (water, wood, small wood and fire - N,E,SE,S). The 'Western Life' directions are NE,SW,W & NW and this is symbolised by the White Tiger. You may have heard of the Dragon and Tiger (left and right) side of a building and Dragon and Tiger shaped hill formations. 

* Footnote

Everything is connected, the planets, the elements and all the living things.
What we experience externally reflects our internal universe. Hence our environment is a reflection of ourselves and vice versa. Balancing the external environment has a direct effect upon our internal condition and helps us to realise our potential. 
