* INTRO
** Geomancy & Feng Shui
  This site explains Chinese Geomancy called Feng Shui. 
It covers the basic theory, touches on advanced metaphysics and includes practical suggestions. 
** Introduction 
Geomancy, or 'Earth Divination', is the reading of energetic interactions on the Earth.

 Geo   = Earth   
 Mancy   = Divination / reading  

Most ancient cultures ( for instance: Aboriginal, African, American Indian, Druid, Celtic, Chinese, Egyptian, Indian, Nordic, Mayan etc.) have or had their own
systems of explanation.

Feng Shui, the Chinese Taoist form of Geomancy, provides the most
comprehensive and well documented type			
** Feng Shui General
Taoism (there is actually no such thing) came from the thoughts and
writings of 'Lao Tzu' who most famously wrote the 'Tao te ching'. His insight
into the working of the cosmos, and how best to live in harmony with it,
formed the philosophical basis of all Taoist practices. (martial arts like Tai
Qi Chuan and Qi Gong, Medicine (Acupuncture, Herbal remedies) and
Internal Alchemy). 

Feng Shui was a later practice derived to harmonise living environments.				

Qi (energy), its creation, qualities and interactions is key.

There are a number of Schools of Feng Shui including: The Form School, The
Compass School, The Black Sect School, The Flying Star School & The
Classical School. 
The Classical School combines theory of various Schools, primarily the
'Form' and 'Compass' Schools, and is what I cover on this site. 

The Classical School combines theory of various Schools, primarily the
'Form' and 'Compass' Schools, and is what I cover on this site. 

In short it breaks down to: 
1.Form: How the topography of the surroundings and the shape of the
 building affects the quality and flow of energy(Qi)
2.Compass orientation: How direction of flow affects energy(Qi).
3.Reading of the above interactions, referencing portents derived from
 'The Five Element' cycle.
4.Personal Horosccope: Can be included to fine tune a consultation. 

** Feng Shui - definition
					
*** Feng (wind) is an invisible fast moving energy (Qi) flowing, like wind,
above the ground and filling every space. 
Imagine 'Feng' as electromagnetically charged particles in the atmosphere.
Its characteristics are dependent upon direction of flow. 

*** Shui (water) is an invisible energy/force inherent in physical things
(mass). It is found within the Earth and is also present within the structure
of buildings and all physical things. Its influence is dependant on scale. 
Imagine 'Shui' as thick viscous invisible energy moving very slowly within
the Earth. It can partly be described as a gravitational force. 

*** The Art of Feng Shui aims to balance these subtle energies and benefit
occupants. 
By observing the types of energy present, interactions can be calculated
and advise on planning and decor given. 

Taoists identified 5 general types of energy (Qi) called the five elements.
How these energies interact is explained using the 'five element cycle'
which is explained diagramically. This is the basis of all calculations in Feng
Shui. 

** Application
					
The 'Lo Pan', a magnetic Compass, is used to assess both the building and
its setting. The 'Lo Pan' includes information on the quality, interactions and
portents (predicted effect) of energy (Qi), by direction. Markings on the 'Lo
Pan' can show detail up to 2 degrees of influence. (please refer to the
'Theory > 8 Directions' section of this site for details). 

A full assessment is based on orientation, topography and a personal
reading. 


** Assessment
An assessment of the site begins outside (macro) and works inwards
(micro). The site setting, larger external environment, is considered first.
Then the internal flow of qi supplying rooms (corridors, passages and
stairwell). Finally the spaces within rooms are calculated for fine tuning (
eg. to assist in furniture layout). 

 Environment  Description  
 Macro environment   Larger site topography, mountains,    
   plains, valleys     
 Immediate environment  Surrounding Landscape, main local    
   features (adjacent buildings, tress,    
   water-courses & roads)     
 Site  The form & shape of "building",    
   relationship to landscape    
 Orientation  Magnetic compass reading (fundemental    
   direction)    
 Internal flows  Main internal circulation of energy(qi).    
 Structure  Structural element, whether exposed or    
   not and material.    
 Individual Spaces  Portents derived from a compass reading.    
 Micro directions  More specific assessment (to within    
   2degs)    
 Horoscope  Personal number/horoscope, determining    
   best orientations 
** Key Aims
 - To determine the best location and building.
 - Ensure an ample supply of good Qi into the property/space and a
 natural flow throughout.
 - To balance a building to suit occupants and maximize potential.
 - Position and orientate furniture, objects, working, living, sleeping
 areas favourably (using portents derived 
** Symbolism & Mythology
Symbolism and mythology are a good way of condensing large amounts of
information into an understandable form. 
Taoism uses symbols to describe specific energy types, however it also uses
a lot of mythological creatures. 
'Taking things literally' can lead to misinterpretation. 
An example: 
The Green Dragon is a great mythological figure in traditional Chinese
culture and is the symbol of the Emperor. 
The Green Dragon is the symbol of fertility and male vigour and also
represents the East, the Wood element and the eastern side of a building.
The Green Dragon has the same attributes as the element Wood. (explained
later in the 5 element section of this site). 
The Green Dragon is the source of rain, water is his life blood and he
breathes fire (Water feeds Wood (the dragon) and creates Fire). 
This interaction relates to what is known as 'The Eastern Life' or the
directions and elements on the Eastern Generative Cycle (water, wood,
small wood and fire - N,E,SE,S). The 'Western Life' directions are NE,SW,W
& NW and this is symbolised by the White Tiger. You may have heard of the
Dragon and Tiger (left and right) side of a building and Dragon and Tiger
shaped hill formations. 
** footnote
Everything is connected, the planets, the elements and all the living things.
What we experience externally reflects our internal universe. Hence our
environment is a reflection of ourselves and vice versa. Balancing the
external environment has a direct effect upon our internal condition and
helps us to realize our potential. 

* Theory
** Introduction
The theory underlying Feng Shui is the same for all Taoist practices
including Tai Qi Chuan, Qi Gong, Acupuncture, internal Alchemy and more.
Taoism is thought to be derived from the teaching and writings of Lao Tzu
(between 600BC & 400BC). Most noteably the poetical 'Tao Te Ching' and
the more detailed 'Hua Hua Ching'. 
Their observations and subsequent understanding developed into a system
of energy classification and calculation. 

Qi is a generic term for energy, from subtle (ethereal, invisable) to coarse
(physical). 

Below is a simple list outlining how "nothing" becomes "something", or the
creation of multiple variations. 

Wu Qi is the original energy source from which everything is created. It is a
unity state energy (consists of one self sufficient force). 
Wu Qi divides, as it transforms into the physical realm, becoming: 

Tai Qi is a state of balanced Yin and Yang. (Infact balanced imbalance, more
later) 

Yin & Yang 
Yin (female, -'ve charge) and 
Yang (male, +'ve charge). 
All things in the physical realm consist of varying amounts of Yin & Yang
(simplistically,female/negative and male/positively charged particles). The
proportion of each determines individual characteristics. 
To graphically describe these proportions: 
Yang was depicted with a solid line and 
Yin was depicted with a broken line. 
Trigrams, a mixture of 3 horizontal yin or yang lines, were used to further
describe quality. 
There are 8 posible, trigrams, combinations of yin and yang. 
Hexigrams, or 6 horizontal lines are a combination of 2 trigrams, which
further describe quality. 
There are 64 possible variations of hexagrams, which can, some say,
correspond to the 64 cordons of DNA. 
Trigrams and Hexigrams are read from bottom up. The bottom line
indicates the most important quality. eg. a Yang line at the bottom
indicates that yang is the most prevalent energy type. Higher lines are a
deminishing hierarchical refinement. The upper most line has the least
importance (although still significant). 

Five Elements (energy types) were identified as having distinct properties
and categorised as Earth, Metal, Water, Wood and Fire . A system of
interactive cycles ( creative and destructive ) was developed. 

Qi (energy) was observed to have differing qualities based on direction of
movement and this was the inspiration behind Feng Shui as an
environmental guide. Feng Shui was originally used in the siting and design
of Palaces and Temples. It later became commonly adopted. Today, in many
parts of Asia it is seen as essential before setting up a business or moving
home. The aim is to balance energy flows to benefit inhabitants. 

The Eight Directions (Bagua) form the basis of the Feng Shui Compass (
Lo Pan ). Eg. Qi (energy) flowing from the south has the qualities of the fire
element. 

Feng Shui literally translates as wind and water. 
Feng (wind) is energy flowing above the ground. 
Shui (water) is energy inherent in the ground or all mass. 

The Lo Pan magnetic compass, used in assessment, shows a variable
'Heavenly' (Feng) sequence of eight directional energy types, shown as
Trigrams, combined with a fixed 'Earthly' (shui) sequence of eight Trigrams
to give a Hexagram (8x8=64 possible) combination portent reading.
Compass readings can however be as specific as to 2 degrees. Personal
Horoscopes are also part of a full assessment. 

Taoist Classical Feng Shui , which I describe here, emerged from the Form
(landscape topography), Compass (directional) and Flying Star (Planetary
movement) Schools. 

In summary: 
*** Wu Qi : Original Source energy > 
*** Tai Qi : Balanced fusion of Yin & Yang energies > (splits into) 
*** Yin : Female energy, -'ve charge & 
*** Yang : Male energy, +'ve charge. > 
*** The 5 Elements : Five general energy types > 
*** The 8 Directions : Eight directional energies > 
*** The 64 Hexagram's : 8x8 interactions, more specific types. 
*** Feng Shui : Environmental interpretation of all the above. 

-----------------------------------------------------------------

In Scientific language they can be thought of as the four fundamental
forces: Gravity, Electromagnetism, Strong Nuclear and Weak
Nuclear. The Taoists included a fifth unifying force called 'Earth'. 
A binary system of Trigrams (3 lines) and Hexagrams (6 lines) was used to
describe and depict qualities. ( solid line=Yang, broken line = Yin) The use
of the '5 Elements' is real and symbolic. eg. The Element Water is the main
energy found in water, but also is the main element in a approximately a
fifth of everything (the planet Mercury and the Kidney organs for instance) 
Each Element describes its own inherent qualities and how it interacts with
the others. eg. Wood feeds Fire (this would be a 'creative' exchange),
whereas, Water douses Fire (this would be a controlling/destructive
exchange). 
Proportion is obviously a factor. eg. one cup of water won't extinguish a
bonfire. 

Two '5 Element Cycles' express generative and controlling exchanges. 

Energy has different qualities based on direction (eg. energy coming from
the south has the property of Fire) and so a system called The 8
Directions (Bagua) was devised to describe energy types based on
Compass orientation. [ these are the same 5 Elements with three additional
distinct flavors. ( small Earth, small Wood & small Metal ) ] 

-----------------------------------------------------------------

** Theory

** Wu Qi

WuQi is "nothingness". The original source from which the cosmos was born
and reborn. It is a unity, a single thing, not of the physical universe. 
A, currently scientifically un-explainable, force that animates living things.
Much more than spirit, the ultimate life force. 
Scientists are aware of the existance, but know nothing of, Dark Matter.
They estimate it constitutes 90% of everything. I believe Wu Qi is many
levels deeper than dark matter. [ "from nothing comes something" . Man
made physical manifestations come from ideas translated into design and
then constructed. "As above, so below" ] 
[ The best way to think of it is as the spark of animating life that enters a
new being at the point of conception. ] 
Everything in the spiritual realm is a unity. 
Everything on the physical plane is a duality. 

** Yin & Yang

Yin and Yang are the two opposing and complimentary energies that
together form the basis of everything present in our perceived world. (
yang= solid line, yin=broken line ) 

Yang (symbolised by a solid line) is the male principle or +'ve charge and 
Yin (symbolised by a broken line) is the female principle or -'ve charge. 
The proportion, quality and interactions of these two forces give rise to all
varied physical manifestations. Yin and Yang balanced and in harmony is
called 'Tai Qi'. The proportion of yin and yang in perfect (imperfect)
harmony is 1: 1.61803. [ Which is also the proportion of 'Phi' and the
'Golden Section' ] 

** Trigrams & Hexagrams
The trigrams and hexagrams are made up of three and six lines
respectively. The illustrate the qualities of energy in proportion of of
yin/yang ( +'ve, -'ve charge ). They are read from bottom to top. The base
line being the most significant up till the top line being the finest of
characteristic. [ the bottom one effectively describing the gerneral sex ] 
** The 5 Elements
The 5 Elements describe the main types of energy in the physical world.
Everything in the physical world (visible or invisible - including air,
electromagnetic fields etc.) has the overall characteristic of one of the
Elements. Understanding their qualities and the way they interact helps us
to implement Feng Shui as well as diagose "well being" in Acupuncture.


** The 8 Directions 
The Chinese discovered that Qi (energy) had differing characteristics
depending upon the direction of movement. They derived a system of
reading these energetic interactions using the main 5 elements qualities. A
Lo Pan is used to obtain information on orientation and the qualities of
energy. It has a magnetic compass at its center with radial and concentric
markings to indicate the main 8,and sub divisions, directions, the former
and later heavenly sequences, portents (fortune) of spaces, Water Dragon
(flows of water, rivers/streams) information and more. 

*** The Baguas
	Bagua (or Pakua) is the Chinese for 8 directions. 

The 8 main directions are: Water, Earth, Wood, Small Wood, Fire, Big
Earth, Metal, Big Metal. 

**** Heavenly Bagua 

The inner Trigrams relate to the "Former Heavenly Sequence". A system
derived to explain the energy of free flowing Feng. 

**** Earthly Bagua

The outer Trigrams relate to the "Later Heavenly Sequence". A system
derived to explain the exchange of energy within a building/space.
Essentially the earth energy (Shui) component inherent in the structure or
gravitational effect . 

The Heavenly Bagua is moveable and the Earthly Bagua is fixed. Correctly
combining and reading these two Bagua's gives the portent of a particular
space. 				
**** Lo Shu (magic square)
Lo Shu is a numeric magic square which said to have been found as
markings the back of a Turtle. It ties in the 8 directions and seasonal
changes and relates to personal horoscope numbers. 
(see horoscope section to calculate your own personal number). 

Odd and even numbers alternate in the periphery of the square, the four
corners are even numbers, and the 5 odd numbers form a cross in the
centre. Each line (vertical, horizontal and diagonal) add up to 15, which is
the number of days in each of the 24 cycles of the Chinese solar year. 
**** Readings
To establish the overall characteristic of Qi ( energy ) within a building , take
a magnetic compass reading at the main door (from the door facing
outwards). 
It is the flow of energy into the building that we are interested in. Further
qualities of energy in seperate rooms is determined by entry flow. This is a
sub-flavour of energy from the original source. 

Whilst each space contains all of the five elements energies - the entry
point is key to determining what element has the most influence. 

>>>>> insert diagram

***** Earthly Bagua
These spaces refer to the general characteristics. The true actual magnetic
orientation of spaces within a room. 
The energetic characteristics can be summarised simply. 

 Space  Quality  Action  
 1 Knowledge  Higher good,info needed  Books, guides  
 2 Family  Fellowship, employees  Photos of  
 3 Wealth, Health  Value, quality  Portrait, Financial docs  
 4 Fame  How you are percieved  Items related to how you  
     wish to be percieved  
 5 Marriage, Business  Unions, Partnerships  Photos,items related to  
 6 Children  New ideas, projects,  Photos, items related to  
   early growth    
 7 Helpful Friends  Helpful  Telephone, Computer  
 8 Career  Lifes Purpose, Fusion  Items relating to  
     vocation, purpose 
     
***** Heavenly Bagua
These "moveable" portents tell us the interactions of free flowing qi
(energy) with the stable state of the above Earthly Bagua. 

 Space  Quality  Portent  
 a  Life, Stable, Balanced  +  
 b  Longevity, Extends Life  ++  
 c  Creates Qi  +++  
 d  Problems, Hinderances  --  
 e  Death, Disconnects  ---  
 f  Five Ghosts, Ancestors  +  
 g  Good fortune, Luck  ++  
 h  Bad influences, Malign  +  

Eg. A south facing house (door to south) has predominantly Fire Qi
(energy) entering it, so the interaction to an eastward wall space ( middle
of East side) would give us an exchange of wood (east) with fire (south) -
wood feeds fire - hence the portent would be very beneficial (as you can see
above and in the diagram, a portent "C" or creates Qi). The energetic
activity in that space is very generative. 

This example is one of the most simple examples, the others are more
complex. A full reading is made by overlaying the former and later heavenly
sequences. Combining the two trigrams (3 lines) gives a hexagram (6 lines)
which describes the energetic properties of a space. 
8 X 8 = 64 hexagrams which relate to the 64 hexagrams of the "I Ching". 

>>>>>> insert portents diagram

***** Flows of Energy
	Flows of Qi and the eddying corner effect explain how the 8 directions are
applicable to a 4 sided room. 

Every space contains all the elements, however we can however determine
which element/s have the greatest influence and the overall characteristic. 

Door position also tells us whether the Qi is more or less active. 

Yang room = left sided doorway, Qi spirals clockwise. Most active, best
for working activities 

Yin room = right sided opening, Qi spirals anti-clockwise. Least active,
best for calming ( bedrooms, relaxation etc) 

Lung room = central opening, Qi spirals both ways, yin quality to the
right side of the room (calming), yang to the left (active) 

>>>>>> insert lung room diagram


* Advanced Theory

** Preamble

When humans lived more simply, in constant and direct contact with nature (working outside), it was easier to connect and absorb basic and subtle energies.

Chinese Taoists identified a supreme natural power which they called "WU QI".

Wu Qi means nothingness (original source) we might call it God. 

One theory is that the "nothingness" is infact "Dark Matter" & "Dark energy" (now believed to be the same thing), or subtle sub-atomic entities. “Dark Matter/Dark energy” is thought by Physicists to makes up the majority of the universe accounting for approximately 90%, with the remaining 10% being the physical universe, or what man knows to exist (planets, people, stuff ,gases, atoms).

Wu Qi fills the universe. 
Connectivity is key in Taoist metaphysics, everything is connected. Even looking at a star, not only are you connected by reflected light, you are seeing the past. 
Connecting with nature helps us to draw upon this source.

Zero point field (ZPF) is well known by scientists, it describes what is left in a vacuum (a state which cannot exist?) or nothingness. This field (or interconnected matrix linking everything in the universe) is full of subatomic activity. ZPF helps explain the Taoists belief that everything is at the centre of the universe as everything is connected to everything else.

It is this connectivity which reveals infinite possibility. Atoms constantly lose and gain energy from the sub-atomic activity occurring in the ZPF and it is this perpetual activity which creates stability.

It is likely that this field is what Taoist Alchemy is tapping into. 

** General Theory

From nothing to something, creation (see diagram opposite). Wu Qi (nothingness/unity) becomes Tai Qi (perfect balance) consisting of  the main Primordial Forces, Heaven (male,positive charge,warm, spirit) and Earth (female, negative charge, cool, life giving).

The state of Tai Qi splits into Yin and Yang the subsequent interaction and proportion gives rise to the 5 elements (something physical). This occurs instantaneously. The 5 elements describe the quality of the main subtle energies at play (duality/physical state) and  is dependant upon the proportion of yin and yang (+'ve, -'ve ) present.

This classification is for general energy quality (the 64 hexagrams give a more detailed description). Each element has its own particular quality (vibration/field of influence). Colours, sounds, shapes, direction of movement, emotions, organs (&functions) and planets have a distinct elemental quality.

The Binary system of Trigrams and Hexagrams was devised by the Taoists to gives a guide to the subtle energies and how they interact. There are 8 trigram variations which when combined (8x8) give rise to the 64 hexagrams (which you may be aware of from the “I Ching”) which describe the quality of energy. A solid line indicates Yang, a broken line indicates Yin. You read from the bottom (earthly level, gives main sex) upwards (heavenly level).


** Primordial Force

Humans store part of the primordial forces.

At conception (sperm and egg forming the first cell) the power to draw in the primordial energy is vast. Each subsequent cell also has the power to draw in the primordial force.

Each organ stores a particular quality. e.g.. The Heart stores part of the original spirit or Primordial force (red, fire, heavenly force), and the right Kidney stores part of the primordial force that gives life (blue, water, earthly force). Chinese Alchemy practices help to connect to these forces and increase vitality.

The fusion of the primordial forces is key to Taoist Alchemy practices, (combining heaven and earth), at this point you are able to alter your DNA, rejuvenate the body, giving you a strong foundation for  spiritual development. Spiritual development is only possible with this grounding as to reach the state of Tai Qi which is the gateway to “nothingness” (god, unity), a balance of heaven and earth is required. ( the balance is a perfect imbalance, see yin & yang balance for detail). NB. The reason the "belly button" is key in "Chinese Taoist Alchemy is that this is the point at which the primordial force first enters our bodies (first cells - connection to mother).


** Feng Shui
  
The Feng Shui looks at the effect of the surrounding environment upon a site and the interaction of subtle energies within confined spaces giving guidance on suitability, arrangement, and how best to utilize. 

The core theory is exactly the same as for all Taoist Esoteric practices.
Humans, living things, objects, everything is connected and affected glued together by a vast ocean of inter connectivity filling every space.
It is best to imagine this “stuff” in terms of energy fields, exerting their own influence and being influenced. Imagine a bunch of waves, the constructive and destructive interference they create (see below). Obviously you can effect this interaction to your benefit.
NB. Nothing is static, everything is energy, so mass is just slowed down energy.
All mass has its own gravitational force (obviously the earth has the greatest effect here).  Albert Einstein redefined the simple Newtonian concept of gravitational attraction by his theory of "unified field theory" or gravity as a field of "space time" influence.

- FENG ( or wind), the stuff we cannot see (in a state of duality) or electromagnetically charged particles.

[ Electro = electric charge ( both positive and negative ).

Magnetic = magnetic charge ( positive pole and negative pole ).

Electromagnetic = the interaction of the two, causing what is called interference. ]

Interference is best visualize as a pond with two stones thrown into the water, the way the ripples interact is interference. You can have constructive interference when the troughs of one meet with the peaks of the other (both with the same amplitude), and destructive interference when the peak of one meets with the peak of the other. So we are dealing with waves and how they interact.

SHUI (water) energy, inherent in physical things, simply described as gravitational force.


** Internal Alchemy

Taoism is not Taoism.The spoken and written word is always misinterpreted. Lao Tzu apparently only wrote the "Tao Te Ching" after being continually pestered. The work is a classic in condensed meaning. It contains a detailed explanation of everything. The "Hua Hua Ching", a later work , is a more straightforward description. Much mystery surrounds Lao Tzu, that he lived to a thousand years, that he didn't live, that the name was an alias.


Whilst the fundamentals are constant, how you connect is individual.
Mantak Chias' works, I found, are the best descriptions and guides (see reading list).

The aim is to advance spiritually. By rooting yourself to the earth (physical) spiritual advancement just happens.
This is achieved by connecting to the earth ( experience blue cool energy coming up from your feet to fill your whole body ), connecting to the heavens ( experienced red, hot energy coming down through the top of your head to fill your whole body ) and sucking in cosmic particle dust through your third eye (forehead). 
To mix and circulate these energies.

The diagram opposite describes it all.

NB. Old Taoists suggested that it would take between 1000-2000 hrs of standing still to connect ( see Mantak Chia "Iron Shirt Qi Gong" for the stance ).
The more you connect, the more you realize that every single bone and muscle is out of alignment, that the flows of energy are blocked. 

Flexibility is life, rigidity is death.

The more flexible you are the better energies flow, the more you will connect to the external forces and the easier it is to connect to your spiritual being.
Always start at the base, good foot contact  ( heel,side,toes,ball ) with the ground, as we want to achieve almost a zero gravity state, an alignment straight up. If your feet are not in correct contact then the rest is out of alignment, the same for knees, hips, shoulders. Think 3d (alignment, twist and muscle pull)  assume you don't know best, and move till you find the right position. The more you practice the more you will know.
Best of all use your stomach brain and not your head brain to find out.

Enough for now! ( check back later ).
