
* colour

Colour is received by the eye as reflected light. 
Each colour has it's own wavelength  ( vibration ) which relates to the energetic characteristic of each of the five elements. 
Reflected light passes from source to the eye and therefore has an effect energetically on everything in the locale. What you see is what you get? If for instance the overall colour you perceive in a room is white then the room energy is affected by the metal colour vibration.

NB. In fact It is when the objects we look at absorb part of the spectrum to which we are sensitive that we perceive the colour of  an object. For instance, if an object absorbs those wavelengths corresponding to the colours red and green then we perceive blue. If an object absorbs those wavelengths corresponding to the colours green and blue then we perceive red.

The 5 element cycle is the key to using colouring the Feng Shui system. Each of the 5 elements have an associative colour:

FIRE: red   
EARTH: yellow   
METAL: white / grey / silver
WATER: blue / black
WOOD: green


colour rgb

 
Once the overall characteristic of Qi within a room has been established by direction you can use an appropriate colour to either 'feed', 'calm', retain 'stable' or 'drain'.

E.g.. If you have a room with the overall characteristic of Qi being WOOD then you would use blue to feed ( water feeds wood ), red to calm (wood feeds fire and therefore calms the energy), green to remain stable( wood + wood = stable ) and yellow to drain ( wood controls earth ). 


* General tips

1. Establish the element of the room by  direction.
Use the 5 element cycle to choose the right colour to manipulate the energy:

a. Feed active areas such as work spaces, living/dining/cooking areas. 
e.g.. if you have a room with the influencing element of fire (door facing south), then use green (wood) to feed.

b. Calm bedrooms. To slow down the activity of energy. 
e.g.. for a fire bedroom, yellow (earth) will calm.
c. Drain bathrooms. To expel waste energy, use the control cycle. e.g.. in a fire bathroom, white (metal) will drain. Fire controls metal.

2. The priority for using colour in areas is: walls first, ceiling then floor.

3. Be subtle when decorating . Pastel colours can be used so long as there is a preponderance of the required pigment.

4. Use spot colour (pictures etc) in specific locations, to feed, calm or drain a space. 

5. Switch off wi-fi internet router when not in use. Especially at night.
