
* Yin And Yang

Yin and Yang lie at the core of all Traditional Chinese explanations of life on earth. ( yang= solid line, yin=broken line )

Everything in the Spiritual realm is a unity.
Everything on the physical plane is a duality.

* Description

Yin and Yang are the two primary forces, they are opposites that compliment.

Yang is the male principle or +'ve charge and Yin is the female principle or -'ve charge.

It is the proportion, quality and interaction of these two forces that give rise to the many varied physical manifestations.
Yin and Yang in perfect harmony is called 'Tai Qi' (symbolized here). The proportion of yin and yang in perfect harmony is 1: 1.61803.

* Balance

The above proportion reoccurs in all natural things. The Fibinachi series is derived from it, and it was used extensively during the Renaissance period and Arts and Crafts Movement (where it is referred to as The Golden Section/ Golden ratio or Phi). It is the proportion of the Buddhist middle way. 

Although 'in balance', 'Tai Qi' is a state of balanced imbalance.

To gain an idea of the balance of yin and yang. Imagine two weights of 1kg and 1.618kg pivoted at a distance 1m and 0.618m (Phi m - symbol illustrated). 

phi
Phi - golden ratio or 1.618

balance

An good example of the occurrence of the above proportion in nature is the pine cone.
Form follows flow.
New growth occurs where the 5 descending spirals of  Yang Qi combine with the 8 ascending spirals of Yin Qi.

5/8ths = 0.618.

5 descending spirals ( yang - from heaven ) intersect with -
8 ascending spirals ( yin - from earth ) creating new growth. 

[ Viktor Shauberger (1885-1958) the Austrian Scientist sought to unlock the secrets of natural energy, and found much common ground with Chinese Metaphysics . His works are a good source of information for those of you seeking a cross-over explanation. ]

* Attributes  (table of yin & yang here)
  The table lists the main characteristics of yin and yang.
* Trigrams & Hexigrams

The Chinese used a binary system to describe the quality of energy.

Yang (+'ve, male) is a solid line and

Yin (-'ve, female) is a broken line. 

The Trigrams - comprising three binary components describe the quality of energy by proportion of yin and yang. ( read from bottom to top ).
Combining two Trigrams produces a Hexagram, which gives more information on the quality of energy.

*** insert table here

The "I-Ching", Chinese book of change, a system of divination uses these hexagrams.
8 x 8 trigrams produce the 64 hexagrams ( combinations ). These relate to the 64 cordons of DNA.
Both Trigrams and Hexagrams are read from bottom to top. From course to more refined. The bottom line gives the macro reading and the upper lines give the detail.

* Indian Energy Centers

The transition from duality to unity is the aim of achieving 'Tai Chi' and beyond. Energy centres of the body also relate to states of being.

The Indian description of these states is an alternative means of understanding. The first four states of being or bodies are states of duality, the last three are the transition to unity.

It was thought that the natural development of these states was achieved by the ages shown below.

*** table of chakras here
