#+TITLE: GENERAL NOTES
* What can I do:
 I have 5
** What can I buy.
*** Flats. Llanhillith, Llaninidod Wells.
*** Farm land. - live in a Tent or build a Tiny House.
*** A Narrow boat.
*** Gold / Silver / Crypto {could be over valued}.
*** Stocks / shares.
** Can I borrow with zero income on 50k?
** Get private investor to manage portfolio
* --------------------------------
* Conspiracy - Research
** Yuri Bezmenov,
   Former KGB Dissident
   Warns America About Socialist Subversion
* Philosophy
  Bryan Magee
 *TODO* [c-c c-t]
 *MY THOUGHTS*
** Block Universe
   If The Block Universe actual is correct:
   And  - there is no "in the NOW"
   Then - Maybe being "in the NOW" might be the way to transcend
          the illusion of "Reality" or the confines of the Block Universe.
** Multi bubble Universe
   ? description before hypothesis
** Individualism & Collectivism & the Whole.
** (based on Alan Watts lecture " The Wisdom Of Insercurity)").
   The Western World based on *Individualism*.
   The State serves the Individual. (or what we were lead to believe)
   Communism is *Collectivism* which is the collective organization of the Individual.
   The *Whole* is something completely different. It is what it is!
   An entity which consists of individuals, where the Individual doesn't really know the
   full nature of the Whole.
** The Illusion of Matter
   Life is a blend of Materialsism & Mysticism.
   Between Sensuality and Spirituality.
   Eg. To much Materialism and Senuality and it becomes boring.
   Too much Spirituality and one becomes to earnist, serious, colourless
   abstract, humourless and lacking "common human connection".
   SPIRITUALISM : shouldn't be dependant upon anything.
   MATERIALiSM is an illusion.
   The only way to enjoy materialism is to disbelieve it and understand it is
   an illusion.
   MATERIALISM is an illusion because:
   Atoms vibrating makes the physical.
   Matter is the result of activity in a constrained space.
   Because we are the same "illusion/vibrating atoms" that's why we
   participate and are conscious of it.
   DOLPHIN (intelligent) choose to live in a less dense environment.
   Easy living, food from the ocean(most easily accessible food source).
   The less dense the environment, the easier it is to loose your connection
   to the physical/material, therefore easier to recognize that the
   material is an illusion.
   You can step back from it see it for what it is, then discover your true
   nature and open up a perception of other things. Thus advance.

* TODO Feng shui - website
* TODO Tao book
* General Immune System
  Vitamin D3 for good all round immunity.
  Other remedies and treatments from the Health Ranger:
  Grapefruit. (definately going to be beneficial).
  Nigella Sativa (black (cumin) seed)? Nigelladean.
  Natto (Japanese herb). Natto Kinaze?
  Quinine bark, relora,

  -------------
   Vitamin D3, C, Zinc
   No vegetable oil
   Eat in a 6 hour period.
   Fasting helping the mitochondria and metobolic cycle.
* Natural Cures / Tea
** Chinese / Thai remedies and cures
   ( From https://absolute-health.org/en/blog/post/fahtalayjon-covid-19.html )
   The benefit of Andrographis paniculata (Far Talai Jone)
Today, we live in a world full of health risk. This is especially so with the global COVID-19 situation and lack of medicaments to prevent or fight it. Therefore, we cannot reject any form of possible measures that can benefit our health or reduce our chances of being infected.

Of late, there had been a lot of hype about how the plant Andrographis paniculata or also lovingly know as Fah Talai Jone (as in picture above) here in Thailand can play a part in protecting one from COVID-19. Let us explore this further and look deeper into the medicinal properties and health benefits it brings together with Dr. Songsaeng Karnchanavisitphol (Expert in German traditional medicine, integrative and anti-aging Specialist).


Q: What are the properties of Far Talai Jone?

Dr.: Fah Talai Jone is actually a traditional Thai herb and had been in used for a very long time for medicinal purposes. It has a Broad-Spectrum function that inhibits the growth of viruses and bacteria. Research studies have found the following benefits:

Helps to cure flu, influenza, relieve inflammation, cough, sore throat, throat inflammation, tonsils, bronchitis and acts as an expectorant

Treatment of skin abscesses

Helps with infections that cause abdominal pain, diarrhea, dysentery and gastroenteritis.

Suppress infection and the growth of pathogens


Q: Can Fah Talai Jone prevent COVID-19?

Dr: This answer is, Fah Talai Jone CANNOT prevent or cure COVID-19. It is only useful in assisting with the treatment of the symptoms that was mentioned in the earlier question.

Q: If you are not sick, how will taking Fah Talai Jone affect your body?

Dr: Fah Talai Jone is a very versatile Thai herb that has a bodily cooling effect. For people who do not have any health conditions, it acts as a medium to rebalance the body. However, taking it long term can lead to a loss of balance and exhaustion, and there are also reports of a decrease in sexual function.


Q: What are the side effects of Fah Talai Jone?

Dr: Most medicaments have benefits and side effects and should be taken under the guidance of a physician. The side effects of taking Fah Talai Jone can be as follows:

abdominal pain

diarrhea

nausea

palpitations

Do seek medical attention immediately if you have the above symptoms.


Q: Since Fah Talai Jone cannot prevent COVID-19, how can we strengthen our immune system?

Dr: One can boost his or her immunity with the follows:

• Reduce frequent outings, wearing protective masks, washing hands, regular exercise and eat healthy.

 • At Absolute Health, we strongly recommend taking the following supplementary immunity boosters:

Turmeric, a well-known natural supplement.

Virulox, a natural pollen extract supplement.

IMC with anti-viral properties, helps with enhance immunity and fights pathogens.

My Collagen is rich in extracts that enhance immunity, stimulate the function of the white blood cells.

Focus on eating foods according to the blood type and in addition controlling meat intake during dinner.

• Reduce sedentary life style and improve quality of health, such as not staying up late.

• Do not over indulge in COVID-19 news if it causes stress and anxiety.

From the information we can clearly understand that Fah Talai Jone do Not prevent the COVID-19 virus and is Not used for disease prevention. Having said that, it is a very useful form of Traditional Thai Medicine that brings about proven results with regards to treating the list of health-related problems mentioned earlier.

By: Dr. Songsaeng Karnchanavisitphol (MD)

Master of German Traditional Medicine

Integrative medicine and Anti-aging medicine Specialist

Medical Article
** Turmeric
   Curry herb/spice
   Virulox Pollen extract
** Green Tea is usually good for everything.
** Dandelion leaf extract
   Dandelion leaf extract blocks spike proteins from binding to
   the ACE2 cell surface receptor
** Pine Needle tea
  A possible remedy for covid and the flu.
  White pine is supposed to be the highest in vitamin C. I use pinion.
*** To define pine trees (Pinus sp),
   look at their needles.
   Pine needles come in clusters of 1-6, most often found in 2-5.
   These clusters are called a fascicle and will have a papery
   sheath at the base, as well as an attached pinecone.

*** Most pine species will have long needles
    but there are a few with shorter ones.
    Meanwhile, spruce or fir needles will be attached
    to the branch rather than a cluster.
*** Common pine varieties
    Douglas Fir
    Ponderosa Pine (not suitable for use by pregnant women)
    Blue Spruce
    Coastal Redwood
*** When foraging,
    be sure to look for local species in your area.
    Research them ahead of time so you know what to look for.
    It is also important that you do not harvest any yew,
    a conifer often mistook as pine, but its needles are poisonous.
*** check for toxinisity.
   Try a little bit, observe your own reactions.
   If feel bad, don't use.
** Star Anise & Shikimic acid.
   Traditional Chinese flu remedy.
** Dandeline Tea & Coffee
** Tamiflu
   Company natural remedy
** Other natural protections
   Other natural compounds have been investigated using molecular docking studies.
   *Nobiletin* is a flavonoid isolated from *citrus peels*. Neohesperidin, a derivative
   of hesperetin, is a flavanone glycoside also found in citrus fruits.
   Glycyrrhizin is a molecular compound extracted from *licorice root*.
   All three of these natural substances also block spike proteins from binding
   to ACE2 receptors. Hydroalcoholic pomegranate peel extract blocks the spike protein
   at the ACE2 receptor with 74 percent efficacy. When its principal constituents were
   tested separately, punicalagin was 64 percent effective, and ellagic acid was 36% percent effective.
** Andrographis paniculata
   (Far Talai Jone)
   Thai remedy for lung infections
* Nanobot inhibiting
** Mule team borax ? (possibly dangerous)
   1 pinch in 1 pint of water
   x3 a day
** Raise your ph level
   Apple Cider Vineger
   2 tblsps mixed in water a day - x3 times a day.
   Reduces candida and raises your ph.

* Philosophy books research
** Master Dogen Shobogenzo
** Rensai buddist monk tang dynasty.
** Upanishads

* Quotes
** Alan Watts
   The reward from an education is the knowledge
   not the certificate or financial outcome.

* Films to watch
** Madame Bovary (1949)
   A provincial doctor's wife's romantic illusions about life and social status lead her to betray
   her naive husband, take on lovers and run up ruinous debts.
** David and Bathsheba (1951)
** Brigadoon (Grace Kelly)
   Two Americans on a hunting trip in Scotland become lost. They encounter a small village, not on the map, called Brigadoon, in which people harbor a mysterious secret, and behave as if they were still living two hundred years in the past.
** Older big list
For the greater glory - mexican communism
Bringing Up Baby
The Passenger 1975 Jack Nicholson
The Apartment
Blow up 1966 Hemmings
In a lonely Place Bogart 1950
Only Angels Have wings Carry grant
Once upon a time in America
Notorious 1946
King Hearts and cornets 1949
The Grapes of Wrath 1949
Paris Texas 1984 nastassia Kinski
Eraserhead 1977
Chelsea girl 1966 warhol
The Big Sleep Bogart
Melancholia Kirsten Dunst 2011
Red River John Wayne
Badlands 1973
Kes
The Good Shepherd (skull and bones matt damon)
The Young Lions 1958 ww2 Brando
Run Silent Run Deep 1958 Subs Gabel & Lancaster
The Horse Soldiers John Wayne Civil War
The Enemy Below 1957 Mitcham Navy film
The Wooden Horse (1950) Prisoner of war escape
The Password is Courage (1962) Pow escape.
Dial M for Murder (1954)
The Browning Version (1951) English school - cuck dour teacher
The Winslow Boy (1948) - navy cadet - stolen postal order
Night and the City (1950) - London spiv - Greco wrestling

** David Lean Films
Ryans daughter,
Those Magnificent Men in their flying machines
The Sound Barrier.
   Blithe Spirit (Noel Coward, Margaret Rutherford)
   The Greatest Story Ever Told. (Jesus)
   In Which We Serve (watched, good navy destroyer, Noel Coward)

** Billy Wilder Films
 1981 Buddy Buddy
 1978 Fedora
 *1974 The Front Page
 1972 Avanti!
 1970 The Private Life of Sherlock Holmes
 1966 The Fortune Cookie
 *1964 Kiss Me, Stupid
 *1963 Irma la Douce
 1961 One, Two, Three
 *1960 The Apartment (directed by)
 *1959 Some Like It Hot
 *1957 Witness for the Prosecution
 1957 Love in the Afternoon
 1957 The Spirit of St. Louis (directed by)
 1955 The Seven Year Itch
 1954 Sabrina
 1953 Stalag 17
 1951 Ace in the Hole
 *1950 Sunset Blvd.
 1948 A Foreign Affair
 1948 The Emperor Waltz
 1945 Death Mills (Documentary short)
 1945 The Lost Weekend
 1944 Double Indemnity
 1943 Five Graves to Cairo
 1942 The Major and the Minor
 1934 Bad Seed (as Billie Wilder)
