#+TITLE:Science Brief
* Richand Feynman
** Jiggling atoms
  Speed = heat
  The faster the speed of the atom the more heat.
  An atom that doesn't loose energy keeps jiggling/ bouncing.
  Balls bouncing, loose speed (energy) passed the energy into patches
  on the floor.
  A drop of water, atoms want to attract each other.
  They want to get inside. At the surface it's open on one side and therefore
  they try to get back into the body. Surface tension, as everyones trying
  to get back into the water body.
  Cool the water, jiggling gets less and less, untill you get ice.
  The atoms get stuck in place, so they don't have enough energy to jiggle
  out of place or roll, so they end up like oranges in a crate.
  If you heat, they loosen and roll around like liquid.
  Heat more then the molecules are too fast/jiggley and escape. That is Steam.
** Fire
  Oxygen wants to be next to Carbon. They like to be tight together.
  They want to snap together.
  If they are not too close together they repel.
  Like a ball rolling up a volcano(shape analogy only)
  they roll up but haven't enoght speed to make it to fall in the hole,
  so they roll back down away. Once they have enough speed they then roll far
  enough to find the hole (attraction) and fall into, or "snap" together.
  Wood is carbon, Co2 wants to be created C & O2 want to snap together.
  Normal state, the air is coming and going against the wood but not enough
  to "snap" join. If you heat/speed up the particles the wood a little to
  get the attraction going, jiggling faster and faster creating a catastrophe
  This increased jiggling makes fire.
  A tree comes primarily out of the air.
  Substance of tree is carbon. It comes from the CO2 in the air.
  The tree pushes out the O2 and leaving the carbon in the tree with H20
  Water comes out of the ground, although came out of the air originally.
  Sunlight / heat seperates the carbon and oxygen, making the molecules
  all jiggly.
  Fire is the recreation of Co2, snapping O2 & Carbon molecules back
  together. The Gas is the Co2 and the light and heat is the suns energy
  released.
  So STORED SUN is what comes out when you burn a log.
  SO : WHY IS THE SUN SO HOT?
  Where does the energy of the sun come from.
  Ans: The suns energy comes from thermonuclear fusion reaction
  Ans: The suns energy comes from thermonuclear fusion reaction.
  Because the suns gravity is so strong, hydrogen atoms fuse together
  to form helium. This releases a massive amount of energy.

  from https://www.reference.com/science/source-sun-s-energy-76b4d49cced4ee03
  "
  The sun's energy comes from thermonuclear fusion reactions. Because the sun's gravity is so strong, hydrogen atoms fuse together to form helium. When they do so, they release a tremendous amount of energy.

More than 90 percent of the matter in the universe is hydrogen, and the sun, like all stars, is primarily composed of hydrogen. Due to its high gravity, the forces in the center of the sun are so strong that hydrogen atoms fuse together to form helium.

Aside from hydrogen and a small amount of helium, all elements were formed in stars that have since died out. When the sun begins running low on hydrogen, it will start fusing helium. It will continue creating heavier elements until it is unable to fuse anything else, at which point it will briefly become a red giant before ejecting most of its matter and becoming a ball of carbon roughly the size of Earth but with a far greater mass.

Shortly after the Big Bang, the matter in the universe was almost exclusively hydrogen. Early stars served as factories that created elements; bigger stars created heavier elements than smaller stars. The heaviest elements can only be created by the violent explosions of supernovae. The Earth's sun is not large enough to cause a supernova.
"

** Rubber Band
** Magnets
** Electricity
** Mirror & Train Puzzle
** Seeing Things
** Big Numbers
** Ways of Thinking

* Taoist Metaphysics
  (Use Aristotelian approach, empirical)
  Look at what's there, everything that is said about it, throw out the contracdiction, use experience.
  Ant-eyed-view & God-eyed-view.
  As Above so Below?
  PRECIS it down to one line for each.
** What is energy?
  E. Britannica
  *Enery, in physics, the capacity for doing work. It may exist in potential, kinetic, thermal, electrical, chemical, nuclear, or other various forms. There are, moreover, heat and work—i.e., energy in the process of transfer from one body to another. After it has been transferred, energy is always designated according to its nature.*
** What is Qi, and the types of qi.
** What is WuQi
** What is TaiQi
** What is Yang
** What is Yin
** *5 Elements*
** What is Earth
** What is Metal
** What is Water
** What is Wood
** What is Fire
